In [5]:
import numpy as np

# Array Basics

In [6]:
fruits = ['apple','banana','cherry','date']

In [7]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [8]:
print(arr_1.dtype) # Output was <U6; suggests the string is apart 6 characters

<U6


In [9]:
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [12]:
print(arr_2.T) # demonstrate dimensions but it does not modify arr_2

[[10 13]
 [11 14]
 [12 15]]


In [13]:
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [14]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [15]:
arr_5 = np.ones((2, 2, 2)) 
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
