In [54]:
import numpy as np

# Generating Random Numbers

In [55]:
# random set of int between 1 and 20 
r_1 = np.random.randint(1, 21, size = 2)
print("r_1:", r_1)

r_1: [ 7 17]


In [56]:
# same as above with 2 columns
r_2 = np.random.randint(1, 21, size = (1, 2))
print("r_2:", r_2)

r_2: [[19  3]]


In [57]:
# random float within 2 rows 1 column
r_3 = np.random.rand(2, 1)
print("r_3:", r_3)

r_3: [[0.26659267]
 [0.45689406]]


In [58]:
# random int between 20 - 100 and 4 rows and 5 columns
r_4 = np.random.randint(20, 101, size = (4, 5))
print("r_4:", r_4)

r_4: [[65 39 97 79 61]
 [99 78 67 60 83]
 [22 31 61 76 96]
 [33 87 71 31 20]]


In [59]:
# random floats between 0 and 1, 4 rows and 5 columns
r_5 = np.random.rand(4, 5)
print("r_5:", r_5)

r_5: [[0.92535319 0.61371615 0.01778553 0.57903335 0.75287367]
 [0.94250462 0.19462482 0.46669774 0.51983933 0.93757115]
 [0.4803043  0.71235087 0.04496965 0.63774046 0.72346324]
 [0.75014219 0.31750011 0.23169989 0.48760424 0.94585855]]


# Generating Random Choices from an Array

In [60]:
students = np.array(['Vieri', 'Jacob', 'Mohammad', 'Armando', 'Craig', 'Anthony', 'Symone', 'Jen', 'Zainab', 'Vanessa', 'Hassan', 'Fadil'])

In [61]:
# random selection using choice
call_on = np.random.choice(students)
print("Random selection:", call_on)

Random selection: Vieri


In [62]:
# random sample 
breakout_groups = np.random.choice(students, size = (3, 4))
print("Breakout groups:")
print(breakout_groups) # in terms of keeping it equal, yes it's effective unless they would wish to place themselves in groups

Breakout groups:
[['Vieri' 'Armando' 'Armando' 'Vanessa']
 ['Anthony' 'Hassan' 'Anthony' 'Hassan']
 ['Jacob' 'Hassan' 'Armando' 'Armando']]


In [63]:
# probabilities list
probabilities = [0.1, 0.05, 0.08, 0.07, 0.05, 0.1, 0.1, 0.05, 0.05, 0.05, 0.3, 0]

# Ensure the probabilities sum to 1
print("Sum of probabilities:", sum(probabilities))  # Should print 1.0

# Weighted random selection
call_on_weighted = np.random.choice(students, size = 5, p = probabilities)
print("Weighted random selections:", call_on_weighted)


Sum of probabilities: 1.0
Weighted random selections: ['Vieri' 'Hassan' 'Mohammad' 'Vieri' 'Armando']


# Generating a Normal Distribution

In [64]:
# mean = 10, stdv = 5 and size 4 rows by 5 columns
bell_curve = np.random.normal(loc = 10, scale = 5, size = (4, 5))
print("Bell curve:")
print(bell_curve)

Bell curve:
[[13.13599399 14.34088876  9.32732897 12.80646007  6.73754886]
 [ 3.02778888  3.30869449 11.15319127 15.73646646  3.21705382]
 [ 0.32481886  7.7491443   6.62801614 12.79622377 18.01466446]
 [16.96095939  7.53996731  2.76798439 14.47326535  6.07364791]]
